-- Esquema y datos iniciales de la Employees API.
-- Se ejecuta una sola vez, en el primer arranque del contenedor de Postgres
-- (volumen vacío). El esquema debe coincidir con el mapeo JPA: Hibernate
-- arranca con ddl-auto=validate y fallaría ante cualquier discrepancia.
-- Las jornadas usan CURRENT_DATE para que el demo siempre muestre datos recientes.

CREATE TABLE employees (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    document_id VARCHAR(20)  NOT NULL UNIQUE,
    email       VARCHAR(100) NOT NULL UNIQUE,
    position    VARCHAR(100),
    hire_date   DATE         NOT NULL,
    status      VARCHAR(20)  NOT NULL
);

CREATE TABLE work_shifts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
    date        DATE   NOT NULL,
    start_time  TIME   NOT NULL,
    end_time    TIME   NOT NULL
);

CREATE INDEX idx_work_shifts_employee_date ON work_shifts (employee_id, date);

-- 30 empleados de ejemplo
INSERT INTO employees (first_name, last_name, document_id, email, position, hire_date, status) VALUES
    ('Ana',            'Gómez',    'CC-1001', 'ana.gomez@example.com',            'Software Engineer',            DATE '2020-01-01', 'ACTIVE'),
    ('Luis',           'Pérez',    'CC-1002', 'luis.perez@example.com',           'DevOps Engineer',              DATE '2021-02-02', 'ACTIVE'),
    ('María',          'Rodríguez', 'CC-1003', 'maria.rodriguez@example.com',     'UX Designer',                  DATE '2022-03-03', 'ACTIVE'),
    ('Carlos',         'Mendoza',  'CC-1004', 'carlos.mendoza@example.com',       'QA Engineer',                  DATE '2023-04-04', 'ACTIVE'),
    ('Lucía',          'Fernández', 'CC-1005', 'lucia.fernandez@example.com',     'Product Manager',              DATE '2024-05-05', 'ACTIVE'),
    ('Javier',         'Ortiz',    'CC-1006', 'javier.ortiz@example.com',         'Backend Engineer',             DATE '2025-06-06', 'ACTIVE'),
    ('Valentina',      'Ríos',     'CC-1007', 'valentina.rios@example.com',       'Data Scientist',               DATE '2020-07-07', 'ACTIVE'),
    ('Andrés',         'Castro',   'CC-1008', 'andres.castro@example.com',        'Frontend Engineer',            DATE '2021-08-08', 'ACTIVE'),
    ('Camila',         'Torres',   'CC-1009', 'camila.torres@example.com',        'Scrum Master',                 DATE '2022-09-09', 'ACTIVE'),
    ('Diego',          'Ramírez',  'CC-1010', 'diego.ramirez@example.com',        'Security Engineer',            DATE '2023-10-10', 'ACTIVE'),
    ('Sofía',          'Herrera',  'CC-1011', 'sofia.herrera@example.com',        'Mobile Engineer',              DATE '2024-11-11', 'ACTIVE'),
    ('Miguel Ángel',   'Cruz',     'CC-1012', 'miguel.angel.cruz@example.com',    'Database Administrator',       DATE '2025-12-12', 'ACTIVE'),
    ('Isabella',       'Moreno',   'CC-1013', 'isabella.moreno@example.com',      'Business Analyst',             DATE '2020-01-13', 'ACTIVE'),
    ('Felipe',         'Vargas',   'CC-1014', 'felipe.vargas@example.com',        'Solutions Architect',          DATE '2021-02-14', 'ACTIVE'),
    ('Daniela',        'Reyes',    'CC-1015', 'daniela.reyes@example.com',        'Tech Lead',                    DATE '2022-03-15', 'ACTIVE'),
    ('Sebastián',      'Guzmán',   'CC-1016', 'sebastian.guzman@example.com',     'Platform Engineer',            DATE '2023-04-16', 'INACTIVE'),
    ('Gabriela',       'Núñez',    'CC-1017', 'gabriela.nunez@example.com',       'QA Automation Engineer',       DATE '2024-05-17', 'ACTIVE'),
    ('Ricardo',        'Salazar',  'CC-1018', 'ricardo.salazar@example.com',      'Site Reliability Engineer',    DATE '2025-06-18', 'ACTIVE'),
    ('Paula',          'Jiménez',  'CC-1019', 'paula.jimenez@example.com',        'Product Designer',             DATE '2020-07-19', 'ACTIVE'),
    ('Óscar',          'Delgado',  'CC-1020', 'oscar.delgado@example.com',        'Integration Engineer',         DATE '2021-08-20', 'ACTIVE'),
    ('Marcela',        'Paredes',  'CC-1021', 'marcela.paredes@example.com',      'Data Engineer',                DATE '2022-09-21', 'ACTIVE'),
    ('Andrés Felipe',  'Mora',     'CC-1022', 'andres.felipe.mora@example.com',   'Full Stack Engineer',          DATE '2023-10-22', 'ACTIVE'),
    ('Tatiana',        'Espinosa', 'CC-1023', 'tatiana.espinosa@example.com',     'DevOps Engineer',              DATE '2024-11-23', 'ACTIVE'),
    ('Jorge Luis',     'Peña',     'CC-1024', 'jorge.luis.pena@example.com',      'Software Engineer',            DATE '2025-12-24', 'ACTIVE'),
    ('Elena',          'Vargas',   'CC-1025', 'elena.vargas@example.com',         'UX Researcher',                DATE '2020-01-25', 'ACTIVE'),
    ('Hernán',         'Quintero', 'CC-1026', 'hernan.quintero@example.com',      'Backend Engineer',             DATE '2021-02-26', 'ACTIVE'),
    ('Natalia',        'Cárdenas', 'CC-1027', 'natalia.cardenas@example.com',     'Machine Learning Engineer',    DATE '2022-03-27', 'ACTIVE'),
    ('Alberto',        'Fuentes',  'CC-1028', 'alberto.fuentes@example.com',      'Network Engineer',             DATE '2023-04-28', 'ACTIVE'),
    ('Renata',         'Duarte',   'CC-1029', 'renata.duarte@example.com',        'Frontend Engineer',            DATE '2024-05-01', 'ACTIVE'),
    ('Esteban',        'Lozano',   'CC-1030', 'esteban.lozano@example.com',       'QA Engineer',                  DATE '2025-06-02', 'ACTIVE');

-- 30 jornadas en 30 días distintos de los últimos 90 días, repartidas entre empleados
INSERT INTO work_shifts (employee_id, date, start_time, end_time) VALUES
    (1,  CURRENT_DATE - INTERVAL '2 days',  TIME '08:00', TIME '17:00'),
    (1,  CURRENT_DATE - INTERVAL '55 days', TIME '09:00', TIME '18:00'),
    (2,  CURRENT_DATE - INTERVAL '5 days',  TIME '10:00', TIME '19:00'),
    (2,  CURRENT_DATE - INTERVAL '67 days', TIME '08:00', TIME '17:00'),
    (3,  CURRENT_DATE - INTERVAL '9 days',  TIME '07:00', TIME '16:00'),
    (3,  CURRENT_DATE - INTERVAL '31 days', TIME '08:30', TIME '17:30'),
    (4,  CURRENT_DATE - INTERVAL '13 days', TIME '08:00', TIME '17:00'),
    (4,  CURRENT_DATE - INTERVAL '79 days', TIME '09:00', TIME '18:00'),
    (5,  CURRENT_DATE - INTERVAL '17 days', TIME '10:00', TIME '19:00'),
    (5,  CURRENT_DATE - INTERVAL '43 days', TIME '08:00', TIME '17:00'),
    (6,  CURRENT_DATE - INTERVAL '21 days', TIME '07:00', TIME '16:00'),
    (6,  CURRENT_DATE - INTERVAL '61 days', TIME '08:30', TIME '17:30'),
    (7,  CURRENT_DATE - INTERVAL '26 days', TIME '08:00', TIME '17:00'),
    (7,  CURRENT_DATE - INTERVAL '84 days', TIME '09:00', TIME '18:00'),
    (8,  CURRENT_DATE - INTERVAL '37 days', TIME '10:00', TIME '19:00'),
    (9,  CURRENT_DATE - INTERVAL '49 days', TIME '08:00', TIME '17:00'),
    (10, CURRENT_DATE - INTERVAL '73 days', TIME '07:00', TIME '16:00'),
    (11, CURRENT_DATE - INTERVAL '1 day',  TIME '08:30', TIME '17:30'),
    (12, CURRENT_DATE - INTERVAL '12 days', TIME '08:00', TIME '17:00'),
    (13, CURRENT_DATE - INTERVAL '48 days', TIME '09:00', TIME '18:00'),
    (14, CURRENT_DATE - INTERVAL '36 days', TIME '10:00', TIME '19:00'),
    (15, CURRENT_DATE - INTERVAL '88 days', TIME '08:00', TIME '17:00'),
    (16, CURRENT_DATE - INTERVAL '25 days', TIME '07:00', TIME '16:00'),
    (17, CURRENT_DATE - INTERVAL '30 days', TIME '08:30', TIME '17:30'),
    (18, CURRENT_DATE - INTERVAL '42 days', TIME '08:00', TIME '17:00'),
    (19, CURRENT_DATE - INTERVAL '4 days',  TIME '09:00', TIME '18:00'),
    (20, CURRENT_DATE - INTERVAL '8 days',  TIME '10:00', TIME '19:00'),
    (21, CURRENT_DATE - INTERVAL '16 days', TIME '08:00', TIME '17:00'),
    (22, CURRENT_DATE - INTERVAL '20 days', TIME '07:00', TIME '16:00'),
    (23, CURRENT_DATE - INTERVAL '54 days', TIME '08:30', TIME '17:30');
